language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install

script:
  - ./vendor/bin/phpmd src/,bin/,tests/ text cleancode,codesize,controversial,design,naming
  - ./vendor/bin/phpcs --standard=PSR2 src/ bin/ tests/
  - ./vendor/bin/phpunit
